import { GeistSans } from "geist/font/sans"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
	title: "journey",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="en"
			className="scroll-smooth bg-black text-white"
		>
			<body className={`${GeistSans.className} min-h-dvh p-12`}>
				{children}
			</body>
		</html>
	)
}
